// @polsia:user-owned — shared zod contract for the Household Pulse: simple,
// deterministic, database-derived counts (never LLM-computed — see
// src/lib/business/pulse.ts). Answers "is everything under control?" at a
// glance.
import { z } from 'zod';

export const PulseSummary = z.object({
  householdId: z.string(),
  attentionCount: z.number().int().min(0),
  waitingCount: z.number().int().min(0),
  upcomingCount: z.number().int().min(0),
  atRiskCount: z.number().int().min(0),
  completedCount: z.number().int().min(0),
  /// Short, specific, deterministic callouts (e.g. "Passport renewal has no
  /// owner.") — never generated by an LLM, never vague marketing copy. See
  /// src/lib/business/pulse.ts for the rule functions that produce these.
  highlights: z.array(z.string()),
  computedAt: z.string().datetime({ offset: true }),
});

export type PulseSummary = z.infer<typeof PulseSummary>;
